# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.IntegerField()),
                ('function_parameters', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('state', models.IntegerField(choices=[(1, 'created'), (2, 'running'), (3, 'finished'), (4, 'failed')])),
                ('dataset_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_in', to='analyzer.Dataset')),
                ('dataset_output', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_out', to='analyzer.Dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
