# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(db_index=True, max_length=60),
        ),
    ]
