# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20160301_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
