# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20160302_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dataset_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_out', to='analyzer.Dataset'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
