# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_dataset_id_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='es_ndocs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='es_fields',
            field=models.ManyToManyField(null=True, to='analyzer.FieldTag'),
        ),
    ]
