# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_auto_20160316_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='es_fields',
            field=models.ManyToManyField(to='analyzer.FieldTag'),
        ),
    ]
