# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_auto_20160316_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='es_ndocs',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
