# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0015_auto_20160316_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='function_name',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
