# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0016_auto_20160416_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='function_name',
            new_name='module_name',
        ),
    ]
